spring.application.name=movieflow

server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.thymeleaf.cache=false

# 매번 테이블을 새로 만들고 데이터를 넣고 싶을 때 (개발 단계)
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update