spring.application.name=movieflow

server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.thymeleaf.cache=false

# 매번 테이블을 새로 만들고 데이터를 넣고 싶을 때 (개발 단계)
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update

# 타임존 설정
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# 이메일 설정
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USER:${SPRING_MAIL_USERNAME:}}
spring.mail.password=${MAIL_PASS:${SPRING_MAIL_PASSWORD:}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_HOST:smtp.gmail.com}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.from=${MAIL_USER}
spring.mail.default-encoding=UTF-8